[package]
name = "fluster_editor"
version = "0.1.0"
authors = ["lprimrose"]
edition = "2018"

[dependencies]
fluster_core = { path = "../fluster_core" }
fluster_graphics = { path = "../fluster_graphics" }
pathfinder_canvas = { git = "https://github.com/kyythane/pathfinder.git" }
pathfinder_color = { git = "https://github.com/kyythane/pathfinder.git" }
pathfinder_content = { git = "https://github.com/kyythane/pathfinder.git" }
pathfinder_geometry = { git = "https://github.com/kyythane/pathfinder.git" }
pathfinder_gpu = { git = "https://github.com/kyythane/pathfinder.git" }
pathfinder_gl = { git = "https://github.com/kyythane/pathfinder.git" }
pathfinder_renderer = { git = "https://github.com/kyythane/pathfinder.git" }
pathfinder_resources = { git = "https://github.com/kyythane/pathfinder.git" }
gl = "0.14"
uuid = { version = "0.8", features = ["v4"] }
conrod_core  = "0.69"
conrod_piston = "0.69"
piston_window = "0.89"